/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "surface-dim": "#d0dbed",
        "tertiary": "#b61722",
        "secondary-container": "#6cf8bb",
        "primary-container": "#c05410",
        "surface-container-highest": "#d9e3f6",
        "error-container": "#ffdad6",
        "inverse-surface": "#27313f",
        "on-surface": "#121c2a",
        "surface-container": "#e6eeff",
        "tertiary-fixed": "#ffdad7",
        "on-background": "#121c2a",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-container": "#fffbff",
        "secondary": "#006c49",
        "on-tertiary-fixed-variant": "#930013",
        "surface-container-low": "#eff4ff",
        "primary-fixed-dim": "#ffb693",
        "on-secondary-fixed": "#002113",
        "outline-variant": "#dec0b4",
        "outline": "#8b7267",
        "primary-fixed": "#ffdbcb",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dee9fc",
        "inverse-primary": "#ffb693",
        "primary": "#9c3f00",
        "secondary-fixed": "#6ffbbe",
        "background": "#f8f9ff",
        "on-primary-container": "#fffbff",
        "secondary-fixed-dim": "#4edea3",
        "surface-bright": "#f8f9ff",
        "surface-tint": "#a04100",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-surface-variant": "#574239",
        "on-primary": "#ffffff",
        "tertiary-container": "#da3437",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#7a3000",
        "on-primary-fixed": "#341000",
        "surface-variant": "#d9e3f6",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-error-container": "#93000a",
        "on-secondary-container": "#00714d",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#005236"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "number-xl": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "title-lg": ["Inter"]
      }
    }
  },
  plugins: [],
}