import React from 'react';
import { useWorkflowStore } from '../store/useWorkflowStore';
import { ConfidenceBadge } from '../components/common/ConfidenceBadge';
import { ExecutiveSummary } from '../components/report/ExecutiveSummary';
import { MarketSnapshot } from '../components/report/MarketSnapshot';
import { TechnicalAnalysisPanel } from '../components/report/TechnicalAnalysisPanel';
import { FundamentalsPanel } from '../components/report/FundamentalsPanel';
import { StrategyPanel } from '../components/report/StrategyPanel';
import { RiskPanel } from '../components/report/RiskPanel';
import { DecisionPanel } from '../components/report/DecisionPanel';

export const Report: React.FC = () => {
  const { workflowState } = useWorkflowStore();

  if (!workflowState) {
    return (
      <div className="flex flex-col items-center justify-center h-[50vh] text-slate-500 print:hidden">
        <svg className="w-12 h-12 mb-4 opacity-50" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>
        <h2 className="text-lg font-semibold text-slate-900">No Report Available</h2>
        <p className="text-sm">Run a workflow to generate a comprehensive printable report.</p>
      </div>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-5xl mx-auto w-full">
      <div className="flex items-center justify-between mb-6 print:hidden">
        <h2 className="text-2xl font-bold text-slate-900 tracking-tight">Comprehensive Audit Report</h2>
        <button onClick={handlePrint} className="px-3 py-1.5 bg-slate-900 text-white rounded-md text-xs font-medium hover:bg-slate-800 flex items-center gap-2 transition">
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M6 9V2h12v7M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg>
          Print / PDF
        </button>
      </div>
      
      <div className="flex flex-col gap-6 print:gap-8">
        <ExecutiveSummary state={workflowState} />
        {workflowState.decision_report && <DecisionPanel report={workflowState.decision_report} />}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 print:grid-cols-2 print:block page-break-inside-avoid">
          <MarketSnapshot report={workflowState.research_report} />
          <TechnicalAnalysisPanel report={workflowState.research_report} />
        </div>
        <FundamentalsPanel report={workflowState.research_report} strategy={workflowState.strategy_report} />
        <StrategyPanel report={workflowState.strategy_report} />
        <RiskPanel report={workflowState.risk_report} />
        <div className="mt-12 pt-6 border-t border-slate-200 text-center text-[10px] font-mono text-slate-400 print:block">
          Generated by Fin AI Cloud • Confidential & Proprietary
        </div>
      </div>
    </div>
  );
};
